import NavBar from './_components/Navbar'
import { AuthProvider } from '@/provider/Auth'
import { Toaster } from '@/components/ui/toaster'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <NavBar />
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
